# Form implementation generated from reading ui file 'GUIROVV1.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtOpenGLWidgets
from PyQt6 import QtCore, QtGui, QtWidgets
import GUI.icon as icon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("ROV CONTROL SYSTEM")
        MainWindow.resize(1085, 872)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stylesheet = QtWidgets.QFrame(parent=self.centralwidget)
        self.stylesheet.setStyleSheet("/* =========================================\n"
                                      "   1. GLOBAL THIẾT LẬP CHUNG (FONT & THEME)\n"
                                      "========================================= */\n"
                                      "* {\n"
                                      "    font-family: \"Rajdhani\", \"Orbitron\", \"Exo 2\", \"Segoe UI\", sans-serif;\n"
                                      "    color: #94A9C4;\n"
                                      "}\n"
                                      "\n"
                                      "QMainWindow, #bg_app {\n"
                                      "    background-color: #060C17;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   2. QUẢN LÝ CÁC PANEL (COMMERCIAL DARK GLASS CARDS)\n"
                                      "========================================= */\n"
                                      "#frm_header, \n"
                                      "#frm_simulate, \n"
                                      "#frm_telemetry_data, \n"
                                      "#frm_power_sys, \n"
                                      "#frm_control_right,\n"
                                      "#frm_control_rov {\n"
                                      "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #0F1B2D, stop:1 #0A1423);\n"
                                      "    border: 1px solid rgba(0, 168, 255, 0.18);\n"
                                      "    border-radius: 8px;\n"
                                      "}\n"
                                      "\n"
                                      "QFrame {\n"
                                      "    border: none;\n"
                                      "}\n"
                                      "\n"
                                      "QLabel {\n"
                                      "    background: transparent;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   3. TIÊU ĐỀ CÁC PANEL CHÍNH (SECTION HEADERS)\n"
                                      "========================================= */\n"
                                      "#lbl_titlename, #lbl_simulate_camera, #lbl_simulate_motion, \n"
                                      "#lbl_telemetry_data, #lbl_power_system, #lbl_control_total {\n"
                                      "    color: #00E5FF;\n"
                                      "    font-size: 11px;\n"
                                      "    font-weight: 800;\n"
                                      "    letter-spacing: 1.5px;\n"
                                      "    text-transform: uppercase;\n"
                                      "    padding: 3px 6px;\n"
                                      "    border-left: 3px solid #00F0FF;\n"
                                      "    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 240, 255, 0.12), stop:1 transparent);\n"
                                      "    border-radius: 2px;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   4. NHÃN PHỤ TRÊN TOP BAR (LABELS)\n"
                                      "========================================= */\n"
                                      "#lbl_mission, #lbl_status_lbl, #lbl_mode, #lbl_connection, #lbl_info_team, #lbl_control_speed {\n"
                                      "    color: #506B88;\n"
                                      "    font-size: 9px;\n"
                                      "    font-weight: bold;\n"
                                      "    text-transform: uppercase;\n"
                                      "    letter-spacing: 0.8px;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   5. THÔNG SỐ TRÊN TOP BAR (VALUES & BADGES)\n"
                                      "========================================= */\n"
                                      "#lbl_mode_value, #lbl_info_value, #lbl_date, #lbl_time, #lbl_nameapp {\n"
                                      "    color: #00D4FF;\n"
                                      "    font-size: 11px;\n"
                                      "    font-weight: bold;\n"
                                      "}\n"
                                      "\n"
                                      "#lbl_status_value, #lbl_connection_value {\n"
                                      "    color: #00FF9D;\n"
                                      "    font-size: 11px;\n"
                                      "    font-weight: bold;\n"
                                      "    text-transform: uppercase;\n"
                                      "    background: rgba(0, 255, 157, 0.08);\n"
                                      "    border-radius: 4px;\n"
                                      "    padding: 1px 6px;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   6. CÁC THÔNG SỐ HIỂN THỊ LỚN (BIG DISPLAY)\n"
                                      "========================================= */\n"
                                      "#lbl_depth_pressure, #lbl_view_compass {\n"
                                      "    color: #FFFFFF;\n"
                                      "    font-size: 18px;\n"
                                      "    font-weight: bold;\n"
                                      "    letter-spacing: 1px;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   7. BUTTONS (PREMIUM COMMERCIAL CONTROLS)\n"
                                      "========================================= */\n"
                                      "QPushButton {\n"
                                      "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #142338, stop:1 #0C1827);\n"
                                      "    color: #00D4FF;\n"
                                      "    border: 1px solid #1D3554;\n"
                                      "    border-radius: 6px;\n"
                                      "    font-weight: bold;\n"
                                      "    font-size: 11px;\n"
                                      "    padding: 4px 10px;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:hover {\n"
                                      "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #00A8FF, stop:1 #0077C8);\n"
                                      "    border: 1px solid #00F0FF;\n"
                                      "    color: #FFFFFF;\n"
                                      "}\n"
                                      "\n"
                                      "QPushButton:pressed {\n"
                                      "    background-color: #0066AA;\n"
                                      "    color: #FFFFFF;\n"
                                      "}\n"
                                      "\n"
                                      "#pbtn_iconheader, #setup_systeam {\n"
                                      "    color: #00D4FF;\n"
                                      "    border: 1px solid transparent;\n"
                                      "    border-radius: 6px;\n"
                                      "    background: transparent;\n"
                                      "}\n"
                                      "#pbtn_iconheader:hover, #setup_systeam:hover {\n"
                                      "    background-color: rgba(0, 212, 255, 0.15);\n"
                                      "    border: 1px solid rgba(0, 240, 255, 0.4);\n"
                                      "}\n"
                                      "#pbtn_iconheader:pressed, #setup_systeam:pressed {\n"
                                      "    background-color: #00A8FF;\n"
                                      "}\n"
                                      "\n"
                                      "/* --- Directional D-Pad Controls --- */\n"
                                      "#pbtn_up, #pbtn_down, #pbtn_left, #pbtn_right {\n"
                                      "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #162840, stop:1 #0F1E31);\n"
                                      "    border: 1px solid #224268;\n"
                                      "    border-radius: 6px;\n"
                                      "}\n"
                                      "#pbtn_up:hover, #pbtn_down:hover, #pbtn_left:hover, #pbtn_right:hover {\n"
                                      "    background-color: rgba(0, 240, 255, 0.25);\n"
                                      "    border: 1px solid #00F0FF;\n"
                                      "    color: #FFFFFF;\n"
                                      "}\n"
                                      "\n"
                                      "#pbtn_stop {\n"
                                      "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #33260A, stop:1 #1E1606);\n"
                                      "    border: 1px solid #FFAB00;\n"
                                      "    color: #FFC107;\n"
                                      "    border-radius: 6px;\n"
                                      "}\n"
                                      "#pbtn_stop:hover {\n"
                                      "    background-color: #FFAB00;\n"
                                      "    color: #000000;\n"
                                      "    border: 1px solid #FFD54F;\n"
                                      "}\n"
                                      "\n"
                                      "/* --- Emergency Stop / Disarm Button --- */\n"
                                      "#pushButton {\n"
                                      "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #381216, stop:1 #220B0D);\n"
                                      "    border: 1px solid #FF3B5C;\n"
                                      "    color: #FF6B81;\n"
                                      "    border-radius: 6px;\n"
                                      "}\n"
                                      "#pushButton:hover {\n"
                                      "    background-color: #FF3B5C;\n"
                                      "    color: #FFFFFF;\n"
                                      "    border: 1px solid #FF8095;\n"
                                      "}\n"
                                      "\n"
                                      "/* --- ARM Motors Button --- */\n"
                                      "#pushButton_3 {\n"
                                      "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #0C3322, stop:1 #072015);\n"
                                      "    border: 1px solid #00FF9D;\n"
                                      "    color: #00FF9D;\n"
                                      "    border-radius: 6px;\n"
                                      "}\n"
                                      "#pushButton_3:hover {\n"
                                      "    background-color: #00FF9D;\n"
                                      "    color: #060B14;\n"
                                      "    border: 1px solid #80FFC9;\n"
                                      "}\n"
                                      "\n"
                                      "/* --- Camera Action Button --- */\n"
                                      "#pbtn_camera {\n"
                                      "    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #112B42, stop:1 #0A1C2C);\n"
                                      "    border: 1px solid #00A8FF;\n"
                                      "    color: #00D4FF;\n"
                                      "    border-radius: 6px;\n"
                                      "}\n"
                                      "#pbtn_camera:hover {\n"
                                      "    background-color: #00A8FF;\n"
                                      "    color: #FFFFFF;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   8. TELEMETRY TABLE (TABLE HEADERS & ITEMS)\n"
                                      "========================================= */\n"
                                      "QHeaderView::section {\n"
                                      "    background-color: #121F33;\n"
                                      "    color: #00D4FF;\n"
                                      "    font-size: 9px;\n"
                                      "    font-weight: bold;\n"
                                      "    text-transform: uppercase;\n"
                                      "    letter-spacing: 1.2px;\n"
                                      "    padding: 5px;\n"
                                      "    border: none;\n"
                                      "    border-bottom: 2px solid #00F0FF;\n"
                                      "}\n"
                                      "\n"
                                      "QTableView {\n"
                                      "    background-color: #060C17;\n"
                                      "    color: #94A9C4;\n"
                                      "    gridline-color: #1B2F4A;\n"
                                      "    border: none;\n"
                                      "    font-size: 11px;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   9. COMBOBOX & OPENGL WIDGETS\n"
                                      "========================================= */\n"
                                      "QComboBox {\n"
                                      "    background-color: #0C1727;\n"
                                      "    border: 1px solid #1D3554;\n"
                                      "    border-radius: 6px;\n"
                                      "    color: #00D4FF;\n"
                                      "    padding: 3px 8px;\n"
                                      "    font-weight: bold;\n"
                                      "}\n"
                                      "\n"
                                      "QComboBox:hover {\n"
                                      "    border: 1px solid #00F0FF;\n"
                                      "    background-color: #112238;\n"
                                      "}\n"
                                      "\n"
                                      "QComboBox QAbstractItemView {\n"
                                      "    background-color: #0A1220;\n"
                                      "    color: #00D4FF;\n"
                                      "    border: 1px solid #00F0FF;\n"
                                      "    border-radius: 6px;\n"
                                      "    selection-background-color: rgba(0, 240, 255, 0.25);\n"
                                      "    selection-color: #FFFFFF;\n"
                                      "    padding: 4px;\n"
                                      "}\n"
                                      "\n"
                                      "QOpenGLWidget {\n"
                                      "    background-color: #040810;\n"
                                      "    border: 1px solid #1B324F;\n"
                                      "    border-radius: 6px;\n"
                                      "}\n"
                                      "\n"
                                      "/* =========================================\n"
                                      "   10. SCROLLBARS (SLEEK MODERN TRACKS)\n"
                                      "========================================= */\n"
                                      "QScrollBar:vertical {\n"
                                      "    background-color: #060C17;\n"
                                      "    width: 8px;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "QScrollBar::handle:vertical {\n"
                                      "    background-color: #1B324F;\n"
                                      "    border-radius: 4px;\n"
                                      "    min-height: 20px;\n"
                                      "}\n"
                                      "QScrollBar::handle:vertical:hover {\n"
                                      "    background-color: #00A8FF;\n"
                                      "}\n"
                                      "QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
                                      "    height: 0px;\n"
                                      "}\n"
                                      "QScrollBar:horizontal {\n"
                                      "    background-color: #060C17;\n"
                                      "    height: 8px;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "QScrollBar::handle:horizontal {\n"
                                      "    background-color: #1B324F;\n"
                                      "    border-radius: 4px;\n"
                                      "    min-width: 20px;\n"
                                      "}\n"
                                      "QScrollBar::handle:horizontal:hover {\n"
                                      "    background-color: #00A8FF;\n"
                                      "}\n"
                                      "QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {\n"
                                      "    width: 0px;\n"
                                      "}")
        self.stylesheet.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.stylesheet.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.stylesheet.setLineWidth(1)
        self.stylesheet.setObjectName("stylesheet")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.stylesheet)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.bg_app = QtWidgets.QFrame(parent=self.stylesheet)
        self.bg_app.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.bg_app.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bg_app.setObjectName("bg_app")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.bg_app)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frm_header = QtWidgets.QFrame(parent=self.bg_app)
        self.frm_header.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_header.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_header.setObjectName("frm_header")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frm_header)
        self.horizontalLayout.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbtn_iconheader = QtWidgets.QPushButton(parent=self.frm_header)
        self.pbtn_iconheader.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon-logo.svg"),
                       QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_iconheader.setIcon(icon)
        self.pbtn_iconheader.setIconSize(QtCore.QSize(40, 40))
        self.pbtn_iconheader.setObjectName("pbtn_iconheader")
        self.horizontalLayout.addWidget(self.pbtn_iconheader)
        self.Vfrm_nameapp = QtWidgets.QFrame(parent=self.frm_header)
        self.Vfrm_nameapp.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Vfrm_nameapp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Vfrm_nameapp.setObjectName("Vfrm_nameapp")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.Vfrm_nameapp)
        self.verticalLayout_21.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.lbl_nameapp = QtWidgets.QLabel(parent=self.Vfrm_nameapp)
        self.lbl_nameapp.setScaledContents(False)
        self.lbl_nameapp.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_nameapp.setObjectName("lbl_nameapp")
        self.verticalLayout_21.addWidget(self.lbl_nameapp)
        self.lbl_titlename = QtWidgets.QLabel(parent=self.Vfrm_nameapp)
        self.lbl_titlename.setObjectName("lbl_titlename")
        self.verticalLayout_21.addWidget(self.lbl_titlename)
        self.horizontalLayout.addWidget(self.Vfrm_nameapp)
        self.frm_header_title = QtWidgets.QFrame(parent=self.frm_header)
        self.frm_header_title.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_header_title.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_header_title.setObjectName("frm_header_title")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frm_header_title)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout.addWidget(self.frm_header_title)
        self.Vfrm_mission = QtWidgets.QFrame(parent=self.frm_header)
        self.Vfrm_mission.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Vfrm_mission.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Vfrm_mission.setObjectName("Vfrm_mission")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Vfrm_mission)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lbl_mission = QtWidgets.QLabel(parent=self.Vfrm_mission)
        self.lbl_mission.setObjectName("lbl_mission")
        self.verticalLayout_7.addWidget(self.lbl_mission)
        self.cb_mission = QtWidgets.QComboBox(parent=self.Vfrm_mission)
        self.cb_mission.setObjectName("cb_mission")
        self.cb_mission.addItem("")
        self.cb_mission.addItem("")
        self.verticalLayout_7.addWidget(self.cb_mission)
        self.horizontalLayout.addWidget(self.Vfrm_mission)
        self.Vfrm_status_sys = QtWidgets.QFrame(parent=self.frm_header)
        self.Vfrm_status_sys.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Vfrm_status_sys.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Vfrm_status_sys.setObjectName("Vfrm_status_sys")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.Vfrm_status_sys)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.lbl_status_lbl = QtWidgets.QLabel(parent=self.Vfrm_status_sys)
        self.lbl_status_lbl.setObjectName("lbl_status_lbl")
        self.verticalLayout_10.addWidget(self.lbl_status_lbl)
        self.lbl_status_value = QtWidgets.QLabel(parent=self.Vfrm_status_sys)
        self.lbl_status_value.setObjectName("lbl_status_value")
        self.verticalLayout_10.addWidget(self.lbl_status_value)
        self.horizontalLayout.addWidget(self.Vfrm_status_sys)
        self.Vfrm_mode_control = QtWidgets.QFrame(parent=self.frm_header)
        self.Vfrm_mode_control.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.Vfrm_mode_control.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Vfrm_mode_control.setObjectName("Vfrm_mode_control")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.Vfrm_mode_control)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lbl_mode = QtWidgets.QLabel(parent=self.Vfrm_mode_control)
        self.lbl_mode.setObjectName("lbl_mode")
        self.verticalLayout_11.addWidget(self.lbl_mode)
        self.lbl_mode_value = QtWidgets.QLabel(parent=self.Vfrm_mode_control)
        self.lbl_mode_value.setObjectName("lbl_mode_value")
        self.verticalLayout_11.addWidget(self.lbl_mode_value)
        self.horizontalLayout.addWidget(self.Vfrm_mode_control)
        self.Hfrm_connection = QtWidgets.QFrame(parent=self.frm_header)
        self.Hfrm_connection.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Hfrm_connection.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Hfrm_connection.setObjectName("Hfrm_connection")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Hfrm_connection)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Vfrm_connection_status = QtWidgets.QFrame(
            parent=self.Hfrm_connection)
        self.Vfrm_connection_status.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.Vfrm_connection_status.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised)
        self.Vfrm_connection_status.setObjectName("Vfrm_connection_status")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(
            self.Vfrm_connection_status)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lbl_connection = QtWidgets.QLabel(
            parent=self.Vfrm_connection_status)
        self.lbl_connection.setObjectName("lbl_connection")
        self.verticalLayout_15.addWidget(self.lbl_connection)
        self.lbl_connection_value = QtWidgets.QLabel(
            parent=self.Vfrm_connection_status)
        self.lbl_connection_value.setObjectName("lbl_connection_value")
        self.verticalLayout_15.addWidget(self.lbl_connection_value)
        self.horizontalLayout_9.addWidget(self.Vfrm_connection_status)
        self.horizontalLayout.addWidget(self.Hfrm_connection)
        self.Vfrm_info_auth = QtWidgets.QFrame(parent=self.frm_header)
        self.Vfrm_info_auth.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Vfrm_info_auth.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Vfrm_info_auth.setObjectName("Vfrm_info_auth")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.Vfrm_info_auth)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.lbl_info_team = QtWidgets.QLabel(parent=self.Vfrm_info_auth)
        self.lbl_info_team.setObjectName("lbl_info_team")
        self.verticalLayout_17.addWidget(self.lbl_info_team)
        self.lbl_info_value = QtWidgets.QLabel(parent=self.Vfrm_info_auth)
        self.lbl_info_value.setObjectName("lbl_info_value")
        self.verticalLayout_17.addWidget(self.lbl_info_value)
        self.horizontalLayout.addWidget(self.Vfrm_info_auth)
        spacerItem = QtWidgets.QSpacerItem(
            573, 19, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.frm_header_date = QtWidgets.QFrame(parent=self.frm_header)
        self.frm_header_date.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_header_date.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_header_date.setObjectName("frm_header_date")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frm_header_date)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout.addWidget(self.frm_header_date)
        self.Vfrm_time = QtWidgets.QFrame(parent=self.frm_header)
        self.Vfrm_time.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Vfrm_time.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Vfrm_time.setObjectName("Vfrm_time")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.Vfrm_time)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(1)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.lbl_time = QtWidgets.QLabel(parent=self.Vfrm_time)
        self.lbl_time.setObjectName("lbl_time")
        self.verticalLayout_18.addWidget(self.lbl_time)
        self.lbl_date = QtWidgets.QLabel(parent=self.Vfrm_time)
        self.lbl_date.setObjectName("lbl_date")
        self.verticalLayout_18.addWidget(self.lbl_date)
        self.horizontalLayout.addWidget(self.Vfrm_time)
        self.setup_systeam = QtWidgets.QPushButton(parent=self.frm_header)
        self.setup_systeam.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/setting-5-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.setup_systeam.setIcon(icon1)
        self.setup_systeam.setIconSize(QtCore.QSize(30, 30))
        self.setup_systeam.setObjectName("setup_systeam")
        self.horizontalLayout.addWidget(self.setup_systeam)
        self.verticalLayout_3.addWidget(self.frm_header)
        self.frm_simulate = QtWidgets.QFrame(parent=self.bg_app)
        self.frm_simulate.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_simulate.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_simulate.setObjectName("frm_simulate")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frm_simulate)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frm_simulate_camera = QtWidgets.QFrame(parent=self.frm_simulate)
        self.frm_simulate_camera.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_simulate_camera.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_simulate_camera.setObjectName("frm_simulate_camera")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frm_simulate_camera)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_simulate_camera = QtWidgets.QLabel(
            parent=self.frm_simulate_camera)
        self.lbl_simulate_camera.setObjectName("lbl_simulate_camera")
        self.verticalLayout_5.addWidget(self.lbl_simulate_camera)
        self.opw_camera = QtOpenGLWidgets.QOpenGLWidget(
            parent=self.frm_simulate_camera)
        self.opw_camera.setObjectName("opw_camera")
        self.verticalLayout_5.addWidget(self.opw_camera)
        self.verticalLayout_5.setStretch(0, 1)
        self.verticalLayout_5.setStretch(1, 20)
        self.horizontalLayout_3.addWidget(self.frm_simulate_camera)
        self.frm_simulate_motion = QtWidgets.QFrame(parent=self.frm_simulate)
        self.frm_simulate_motion.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_simulate_motion.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_simulate_motion.setObjectName("frm_simulate_motion")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frm_simulate_motion)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_simulate_motion = QtWidgets.QLabel(
            parent=self.frm_simulate_motion)
        self.lbl_simulate_motion.setObjectName("lbl_simulate_motion")
        self.verticalLayout_6.addWidget(self.lbl_simulate_motion)
        self.opw_motion = QtOpenGLWidgets.QOpenGLWidget(
            parent=self.frm_simulate_motion)
        self.opw_motion.setObjectName("opw_motion")
        self.verticalLayout_6.addWidget(self.opw_motion)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 20)
        self.horizontalLayout_3.addWidget(self.frm_simulate_motion)
        self.frm_simulate_control_depth_led = QtWidgets.QFrame(
            parent=self.frm_simulate)
        self.frm_simulate_control_depth_led.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_simulate_control_depth_led.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised)
        self.frm_simulate_control_depth_led.setObjectName(
            "frm_simulate_control_depth_led")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(
            self.frm_simulate_control_depth_led)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frm_compass_depth = QtWidgets.QFrame(
            parent=self.frm_simulate_control_depth_led)
        self.frm_compass_depth.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_compass_depth.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_compass_depth.setObjectName("frm_compass_depth")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frm_compass_depth)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lbl_depth_pressure = QtWidgets.QLabel(
            parent=self.frm_compass_depth)
        self.lbl_depth_pressure.setObjectName("lbl_depth_pressure")
        self.verticalLayout_9.addWidget(self.lbl_depth_pressure)
        self.Hfrm_depth_pressure = QtWidgets.QFrame(
            parent=self.frm_compass_depth)
        self.Hfrm_depth_pressure.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.Hfrm_depth_pressure.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Hfrm_depth_pressure.setObjectName("Hfrm_depth_pressure")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(
            self.Hfrm_depth_pressure)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_9.addWidget(self.Hfrm_depth_pressure)
        self.lbl_view_compass = QtWidgets.QLabel(parent=self.frm_compass_depth)
        self.lbl_view_compass.setObjectName("lbl_view_compass")
        self.verticalLayout_9.addWidget(self.lbl_view_compass)
        self.frm_simulate_view_bottom = QtWidgets.QFrame(
            parent=self.frm_compass_depth)
        self.frm_simulate_view_bottom.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_simulate_view_bottom.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised)
        self.frm_simulate_view_bottom.setObjectName("frm_simulate_view_bottom")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(
            self.frm_simulate_view_bottom)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_9.addWidget(self.frm_simulate_view_bottom)
        self.verticalLayout_9.setStretch(0, 2)
        self.verticalLayout_9.setStretch(1, 9)
        self.verticalLayout_9.setStretch(2, 2)
        self.verticalLayout_9.setStretch(3, 6)
        self.verticalLayout_8.addWidget(self.frm_compass_depth)
        self.horizontalLayout_3.addWidget(self.frm_simulate_control_depth_led)
        self.horizontalLayout_3.setStretch(0, 8)
        self.horizontalLayout_3.setStretch(1, 8)
        self.horizontalLayout_3.setStretch(2, 2)
        self.verticalLayout_3.addWidget(self.frm_simulate)
        self.frm_control = QtWidgets.QFrame(parent=self.bg_app)
        self.frm_control.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_control.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_control.setObjectName("frm_control")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frm_control)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frm_telemetry_data = QtWidgets.QFrame(parent=self.frm_control)
        self.frm_telemetry_data.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_telemetry_data.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_telemetry_data.setObjectName("frm_telemetry_data")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frm_telemetry_data)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.lbl_telemetry_data = QtWidgets.QLabel(
            parent=self.frm_telemetry_data)
        self.lbl_telemetry_data.setObjectName("lbl_telemetry_data")
        self.verticalLayout_20.addWidget(self.lbl_telemetry_data)
        self.tabl_data = QtWidgets.QTableView(parent=self.frm_telemetry_data)
        self.tabl_data.setObjectName("tabl_data")
        self.verticalLayout_20.addWidget(self.tabl_data)
        self.horizontalLayout_4.addWidget(self.frm_telemetry_data)
        self.frm_data_follow = QtWidgets.QFrame(parent=self.frm_control)
        self.frm_data_follow.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_data_follow.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_data_follow.setObjectName("frm_data_follow")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frm_data_follow)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frm_power_sys = QtWidgets.QFrame(parent=self.frm_data_follow)
        self.frm_power_sys.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_power_sys.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_power_sys.setObjectName("frm_power_sys")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frm_power_sys)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.lbl_power_system = QtWidgets.QLabel(parent=self.frm_power_sys)
        self.lbl_power_system.setObjectName("lbl_power_system")
        self.verticalLayout_19.addWidget(self.lbl_power_system)
        self.ogl_powersys = QtOpenGLWidgets.QOpenGLWidget(
            parent=self.frm_power_sys)
        self.ogl_powersys.setObjectName("ogl_powersys")
        self.verticalLayout_19.addWidget(self.ogl_powersys)
        self.verticalLayout_19.setStretch(0, 1)
        self.verticalLayout_19.setStretch(1, 11)
        self.verticalLayout_14.addWidget(self.frm_power_sys)
        self.horizontalLayout_4.addWidget(self.frm_data_follow)
        self.frm_control_right = QtWidgets.QFrame(parent=self.frm_control)
        self.frm_control_right.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_control_right.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_control_right.setObjectName("frm_control_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frm_control_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_control_total = QtWidgets.QLabel(
            parent=self.frm_control_right)
        self.lbl_control_total.setObjectName("lbl_control_total")
        self.verticalLayout_4.addWidget(self.lbl_control_total)
        self.frm_control_rov = QtWidgets.QFrame(parent=self.frm_control_right)
        self.frm_control_rov.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_control_rov.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_control_rov.setObjectName("frm_control_rov")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frm_control_rov)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frm_control_rov_yaw = QtWidgets.QFrame(
            parent=self.frm_control_rov)
        self.frm_control_rov_yaw.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_control_rov_yaw.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_control_rov_yaw.setObjectName("frm_control_rov_yaw")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(
            self.frm_control_rov_yaw)
        self.verticalLayout_13.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frm_control_rov_yaw_button = QtWidgets.QFrame(
            parent=self.frm_control_rov_yaw)
        self.frm_control_rov_yaw_button.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_control_rov_yaw_button.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised)
        self.frm_control_rov_yaw_button.setObjectName(
            "frm_control_rov_yaw_button")
        self.gridLayout = QtWidgets.QGridLayout(
            self.frm_control_rov_yaw_button)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(9)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem1 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.pbtn_left = QtWidgets.QPushButton(
            parent=self.frm_control_rov_yaw_button)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.pbtn_left.sizePolicy().hasHeightForWidth())
        self.pbtn_left.setSizePolicy(sizePolicy)
        self.pbtn_left.setContextMenuPolicy(
            QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/arrows/arrow-left-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_left.setIcon(icon2)
        self.pbtn_left.setObjectName("pbtn_left")
        self.gridLayout.addWidget(self.pbtn_left, 2, 0, 1, 1)
        self.pbtn_right = QtWidgets.QPushButton(
            parent=self.frm_control_rov_yaw_button)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/arrows/arrow-right-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_right.setIcon(icon3)
        self.pbtn_right.setObjectName("pbtn_right")
        self.gridLayout.addWidget(self.pbtn_right, 2, 2, 1, 1)
        self.pbtn_up = QtWidgets.QPushButton(
            parent=self.frm_control_rov_yaw_button)
        font = QtGui.QFont()
        font.setFamily("Rajdhani")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.pbtn_up.setFont(font)
        self.pbtn_up.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/arrows/arrow-up-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_up.setIcon(icon4)
        self.pbtn_up.setObjectName("pbtn_up")
        self.gridLayout.addWidget(self.pbtn_up, 1, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.gridLayout.addItem(spacerItem2, 4, 1, 1, 1)
        self.pbtn_stop = QtWidgets.QPushButton(
            parent=self.frm_control_rov_yaw_button)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/arrows/crosshairs-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_stop.setIcon(icon5)
        self.pbtn_stop.setObjectName("pbtn_stop")
        self.gridLayout.addWidget(self.pbtn_stop, 2, 1, 1, 1)
        self.pbtn_down = QtWidgets.QPushButton(
            parent=self.frm_control_rov_yaw_button)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/arrows/arrow-down-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_down.setIcon(icon6)
        self.pbtn_down.setObjectName("pbtn_down")
        self.gridLayout.addWidget(self.pbtn_down, 3, 1, 1, 1)
        self.verticalLayout_13.addWidget(self.frm_control_rov_yaw_button)
        self.horizontalLayout_8.addWidget(self.frm_control_rov_yaw)
        self.frm_control_rov_right_bottom = QtWidgets.QFrame(
            parent=self.frm_control_rov)
        self.frm_control_rov_right_bottom.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_control_rov_right_bottom.setFrameShadow(
            QtWidgets.QFrame.Shadow.Raised)
        self.frm_control_rov_right_bottom.setObjectName(
            "frm_control_rov_right_bottom")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(
            self.frm_control_rov_right_bottom)
        self.verticalLayout_16.setContentsMargins(9, 0, 9, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        spacerItem3 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_16.addItem(spacerItem3)
        self.pbtn_control_depth_increase = QtWidgets.QPushButton(
            parent=self.frm_control_rov_right_bottom)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/arrows/double-up-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_control_depth_increase.setIcon(icon7)
        self.pbtn_control_depth_increase.setObjectName(
            "pbtn_control_depth_increase")
        self.verticalLayout_16.addWidget(self.pbtn_control_depth_increase)
        self.pbtn_control_depth_decrease = QtWidgets.QPushButton(
            parent=self.frm_control_rov_right_bottom)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/arrows/double-down-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_control_depth_decrease.setIcon(icon8)
        self.pbtn_control_depth_decrease.setObjectName(
            "pbtn_control_depth_decrease")
        self.verticalLayout_16.addWidget(self.pbtn_control_depth_decrease)
        self.pushButton = QtWidgets.QPushButton(
            parent=self.frm_control_rov_right_bottom)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/arrows/stop-svgrepo-com.svg"),
                        QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon9)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_16.addWidget(self.pushButton)
        spacerItem4 = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_16.addItem(spacerItem4)
        self.horizontalLayout_8.addWidget(self.frm_control_rov_right_bottom)
        self.verticalLayout_4.addWidget(self.frm_control_rov)
        self.frm_control_speed = QtWidgets.QFrame(
            parent=self.frm_control_right)
        self.frm_control_speed.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_control_speed.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_control_speed.setObjectName("frm_control_speed")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frm_control_speed)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_control_speed = QtWidgets.QLabel(
            parent=self.frm_control_speed)
        self.lbl_control_speed.setObjectName("lbl_control_speed")
        self.horizontalLayout_6.addWidget(self.lbl_control_speed)
        self.lbl_control_speed_number = QtWidgets.QLabel(
            parent=self.frm_control_speed)
        self.lbl_control_speed_number.setObjectName("lbl_control_speed_number")
        self.horizontalLayout_6.addWidget(self.lbl_control_speed_number)
        self.pbtn_speed_increase = QtWidgets.QPushButton(
            parent=self.frm_control_speed)
        self.pbtn_speed_increase.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/arrows/plus-svgrepo-com.svg"),
                         QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_speed_increase.setIcon(icon10)
        self.pbtn_speed_increase.setObjectName("pbtn_speed_increase")
        self.horizontalLayout_6.addWidget(self.pbtn_speed_increase)
        self.pbtn_speed_decrease = QtWidgets.QPushButton(
            parent=self.frm_control_speed)
        self.pbtn_speed_decrease.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/arrows/minus-svgrepo-com.svg"),
                         QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_speed_decrease.setIcon(icon11)
        self.pbtn_speed_decrease.setObjectName("pbtn_speed_decrease")
        self.horizontalLayout_6.addWidget(self.pbtn_speed_decrease)
        self.verticalLayout_4.addWidget(self.frm_control_speed)
        self.frm_control_led = QtWidgets.QFrame(parent=self.frm_control_right)
        self.frm_control_led.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frm_control_led.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frm_control_led.setObjectName("frm_control_led")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frm_control_led)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pbtn_led_onoff = QtWidgets.QPushButton(
            parent=self.frm_control_led)
        self.pbtn_led_onoff.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icon/flashlight-svgrepo-com.svg"),
                         QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_led_onoff.setIcon(icon12)
        self.pbtn_led_onoff.setObjectName("pbtn_led_onoff")
        self.horizontalLayout_7.addWidget(self.pbtn_led_onoff)
        self.lbl_control_led_number = QtWidgets.QLabel(
            parent=self.frm_control_led)
        self.lbl_control_led_number.setObjectName("lbl_control_led_number")
        self.horizontalLayout_7.addWidget(self.lbl_control_led_number)
        self.pbtn_led_increase = QtWidgets.QPushButton(
            parent=self.frm_control_led)
        self.pbtn_led_increase.setText("")
        self.pbtn_led_increase.setIcon(icon10)
        self.pbtn_led_increase.setObjectName("pbtn_led_increase")
        self.horizontalLayout_7.addWidget(self.pbtn_led_increase)
        self.pbtn_led_decrease = QtWidgets.QPushButton(
            parent=self.frm_control_led)
        self.pbtn_led_decrease.setText("")
        self.pbtn_led_decrease.setIcon(icon11)
        self.pbtn_led_decrease.setObjectName("pbtn_led_decrease")
        self.horizontalLayout_7.addWidget(self.pbtn_led_decrease)
        self.verticalLayout_4.addWidget(self.frm_control_led)
        self.Hfrm_control_action = QtWidgets.QFrame(
            parent=self.frm_control_right)
        self.Hfrm_control_action.setFrameShape(
            QtWidgets.QFrame.Shape.StyledPanel)
        self.Hfrm_control_action.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Hfrm_control_action.setObjectName("Hfrm_control_action")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(
            self.Hfrm_control_action)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.pbtn_camera = QtWidgets.QPushButton(
            parent=self.Hfrm_control_action)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icon/camera-svgrepo-com.svg"),
                         QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pbtn_camera.setIcon(icon13)
        self.pbtn_camera.setObjectName("pbtn_camera")
        self.horizontalLayout_11.addWidget(self.pbtn_camera)
        self.pushButton_3 = QtWidgets.QPushButton(
            parent=self.Hfrm_control_action)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icon/robotic-arm-svgrepo-com.svg"),
                         QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_3.setIcon(icon14)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_11.addWidget(self.pushButton_3)
        self.verticalLayout_4.addWidget(self.Hfrm_control_action)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 8)
        self.verticalLayout_4.setStretch(2, 3)
        self.verticalLayout_4.setStretch(3, 3)
        self.verticalLayout_4.setStretch(4, 3)
        self.horizontalLayout_4.addWidget(self.frm_control_right)
        self.horizontalLayout_4.setStretch(0, 6)
        self.horizontalLayout_4.setStretch(1, 3)
        self.horizontalLayout_4.setStretch(2, 4)
        self.verticalLayout_3.addWidget(self.frm_control)
        self.verticalLayout_3.setStretch(1, 7)
        self.verticalLayout_3.setStretch(2, 5)
        self.verticalLayout_2.addWidget(self.bg_app)
        self.verticalLayout.addWidget(self.stylesheet)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_nameapp.setText(_translate("MainWindow", "CNC NExora"))
        self.lbl_titlename.setText(_translate(
            "MainWindow", "ROV CONTROL SYSTEM"))
        self.lbl_mission.setText(_translate("MainWindow", "MODEL"))
        self.cb_mission.setItemText(0, _translate("MainWindow", "3DC"))
        self.cb_mission.setItemText(1, _translate("MainWindow", "6DC"))
        self.lbl_status_lbl.setText(_translate("MainWindow", "STATUS"))
        self.lbl_status_value.setText(_translate("MainWindow", "ACTIVE"))
        self.lbl_mode.setText(_translate("MainWindow", "ROV MODE"))
        self.lbl_mode_value.setText(_translate("MainWindow", "MANUAL"))
        self.lbl_connection.setText(_translate("MainWindow", "🛜 Connection"))
        self.lbl_connection_value.setText(_translate("MainWindow", "STRONG"))
        self.lbl_info_team.setText(_translate("MainWindow", "TEAM"))
        self.lbl_info_value.setText(_translate("MainWindow", "CNC NExora"))
        self.lbl_time.setText(_translate("MainWindow", "14:35:42"))
        self.lbl_date.setText(_translate("MainWindow", "VN 2026/07/06"))
        self.lbl_simulate_camera.setText(
            _translate("MainWindow", "LIVE CAMERA FEED"))
        self.lbl_simulate_motion.setText(
            _translate("MainWindow", "3D MOTION & POSITION"))
        self.lbl_depth_pressure.setText(
            _translate("MainWindow", "DEPTH & PRESSURE"))
        self.lbl_view_compass.setText(_translate("MainWindow", "COMPASS"))
        self.lbl_telemetry_data.setText(
            _translate("MainWindow", "TELEMETRY DATA"))
        self.lbl_power_system.setText(
            _translate("MainWindow", "POWER SYSTEMS"))
        self.lbl_control_total.setText(
            _translate("MainWindow", "ROV CONTROLS"))
        self.pbtn_left.setText(_translate("MainWindow", "LEFT"))
        self.pbtn_right.setText(_translate("MainWindow", "RIGHT"))
        self.pbtn_up.setText(_translate("MainWindow", "UP"))
        self.pbtn_stop.setText(_translate("MainWindow", "HOVER"))
        self.pbtn_down.setText(_translate("MainWindow", "DOWN"))
        self.pbtn_control_depth_increase.setText(
            _translate("MainWindow", " ASCEND"))
        self.pbtn_control_depth_decrease.setText(
            _translate("MainWindow", "DESCEND"))
        self.pushButton.setText(_translate("MainWindow", "   STOP "))
        self.lbl_control_speed.setText(_translate("MainWindow", "SPEED :"))
        self.lbl_control_speed_number.setText(_translate("MainWindow", "128"))
        self.lbl_control_led_number.setText(_translate("MainWindow", "100%"))
        self.pbtn_camera.setText(_translate("MainWindow", "CAMERA"))
        self.pushButton_3.setText(_translate("MainWindow", "ARM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
